apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.name }}
spec:
  acme:
    email: {{ .Values.issuerEmail }}
    privateKeySecretRef:
      name: {{ .Values.name }}
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          digitalocean:
            # Kubernetes secret that contains the DO API token.
            # Must be in the same namespace as the Issuer CRD.
            tokenSecretRef:
              name: digitalocean-dns
              key: access-token